version: '3.7'

services:
  blockscout:
    image: blockscout/blockscout:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "ecto://postgres:postgres@postgres/blockscout_db"
      ETHEREUM_JSON_RPC_HTTP_URL: "https://virtual.sonic.rpc.tenderly.co/68643e3c-dc3e-42f1-bde3-ed8dbccabbe0"
      SECRET_KEY_BASE: "68643e3c-dc3e-42f1-bde3-ed8dbccabbe0"
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "blockscout_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
